---
# File: main.yml
# Type: task
# Part: System/Security

- name: Security | Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Security | Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
#  notify: Restart sshd # currently bugged on ansible for trusty

- name: Security | Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
#  notify: Restart sshd # currently bugged on ansible for trusty

- name: Security | Install rootkit detection
  action: apt pkg=chkrootkit state=present
- name: Security | Install rootkit detection
  action: apt pkg=rkhunter state=present

#- name: Security | Install unattended-upgrades
#  action: apt pkg=unattended-upgrades state=present

#- name: Security | Adjust APT update intervals
#  action: copy src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

#- name: Security | Copy debconf selections so that Postfix can configure itself non-interactively
#  copy: src=postfix_selections  dest=/tmp/postfix_selections

#- name: Security | Set up Postfix to relay mail
#  action: command debconf-set-selections /tmp/postfix_selections

#- name: Security | Install logwatch
#  action: apt pkg=logwatch state=installed
#
#- name: Security | Make logwatch mail $logwatch_email daily
#  action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present

# Set firewall
#- name: Security | Firewall allow ssh (ufw enable has to be run manually)
#  action: command ufw allow ssh
#- name: Security | Firewall allow http (ufw enable has to be run manually)
#  action: command ufw allow http
#- name: Security | Firewall allow https (ufw enable has to be run manually)
#  action: command ufw allow https

#- name: Security | Prevent IP spoofing
#  action: lineinfile dest=/etc/host.conf regexp="^order" line="order bind,hosts" state=present
#- name: Security | Prevent IP spoofing
#  action: lineinfile dest=/etc/host.conf regexp="^nospoof" line="nospoof on" state=present

#- name: Security | Intrusion detection PSAD
#  action: apt pkg=psad state=present
#- name: Security | Configure PSAD
#  action: lineinfile dest=/etc/psad/psad.conf regexp="^EMAIL_ADDRESSES" line="EMAIL_ADDRESSES             $logwatch_email;" state=present
#- name: Security | Configure PSAD (IPtables)
#  action: command iptables -A INPUT -j LOG
#- name: Security | Configure PSAD (IPtables)
#  action: command iptables -A FORWARD -j LOG
#- name: Security | Configure PSAD (IP6tables)
#  action: command ip6tables -A INPUT -j LOG
#- name: Security | Configure PSAD (IP6tables)
#  action: command ip6tables -A FORWARD -j LOG
#- name: Security | Configure PSAD (update signatures)
#  action: command psad --sig-update

#- name: Security | SELinux
#  action: apt pkg=apparmor state=present
#- name: Security | SELinux
#  action: apt pkg=apparmor-profiles state=present

#- name: Security | DenyHosts
#  action: apt pkg=denyhosts state=present

#- name: Security | Secure shm
#  action: lineinfile dest=/etc/fstab  regexp="^tmpfs" line="tmpfs     /dev/shm     tmpfs     defaults,noexec,nosuid     0     0" state=present

#- name: Security | Reboot
#  action: command reboot