---
# Type: task
# Part: Nginx

- name: Nginx | Deploy supervisor service configuration
  template: src=supervisor_conf.d_nginx.conf.j2 dest=/etc/supervisor/conf.d/nginx.conf owner=root group=root mode=0644 backup=no
  register: result
- name: Nginx | Start supervisor service
  supervisorctl: name=nginx state=started config=/etc/supervisor/supervisord.conf
