---
# File: main.yml
# Type: task
# Part: Ansible/Setup


## Install
- name: Setup | Install ansible required packages
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - python-dev
    - python-pip
    - python-pycurl
    - python-software-properties
- name: Setup | Install ansible locally
  ignore_errors: True
  pip: name={{ item }} state=latest
  # extra_args="--proxy http://{{ pip_proxy }}"
  with_items:
    - ansible
- name: Setup | Check if local ansible folder exists
  stat: path=/etc/ansible
  register: etc_ansible_path
- name: Setup | Install ansible locally
  shell: mkdir /etc/ansible; echo 'localhost ansible_connection=local' > /etc/ansible/hosts
         creates=/etc/ansible/hosts
  when: not etc_ansible_path.stat.exists
