---
# File: main.yml
# Type: task
# Part: Interfaces

- name: Interfaces | Deploy configuration
  template: src=network_interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644
  notify: restart networking
