---
# File: main.yml
# Type: defaults
# Part: System/Mail

system_mail_apt_modules:
  - postfix
  - postfix-mysql
  - dovecot-core
  - dovecot-imapd
  - dovecot-pop3d
  - dovecot-lmtpd
  - dovecot-mysql

# SSL configs for mail server
# If self_signed is set to true, a private key and self-signed SSL cert will be generated and placed in the paths above
system_mail_ssl:
  self_signed: true
  generate_cert_subject: "/C=US/O={{ system_mail_default_domain }}/CN={{ system_mail_default_domain }}"
