---
# File: main.yml
# Type: task
# Part: OpenVPN | ARM

- name: OpenVPN | Install required packages
  apt: name={{ item }} state=latest
  with_items:
    - liblzo2-dev
    - libpam0g-dev
    - libssl-dev
- name: OpenVPN | ARM | Fetch package
  get_url: url=http://swupdate.openvpn.org/community/releases/openvpn-{{ openvpn_arm_version }}.tar.gz dest=/opt
    sha256sum={{ openvpn_arm_shasum }}
  register: result
- name: OpenVPN | ARM | Extract package
  shell: mkdir -p /opt/tmp/openvpn-{{ openvpn_arm_version }}; tar -xzf /opt/openvpn-{{ openvpn_arm_version }}.tar.gz -C /opt/tmp/openvpn-{{ openvpn_arm_version }} --strip-components 1
  when: result | changed
- name: OpenVPN | ARM | Check version
  shell: openvpn --version | head -n 1 | cut -c 9-13
  ignore_errors: True
  register: openvpn_version
- name: OpenVPN | ARM | Configure package
  when: openvpn_version.stdout != '{{ openvpn_arm_version }}'
  shell: ./configure --host=arm-linux-gnueabihf --prefix=/usr/local
         chdir=/opt/tmp/openvpn-{{ openvpn_arm_version }}
         creates=/opt/tmp/openvpn-{{ openvpn_arm_version }}/config.status
- name: OpenVPN | ARM | Make package
  when: openvpn_version.stdout != '{{ openvpn_arm_version }}'
  shell: make && make install
         chdir=/opt/tmp/openvpn-{{ openvpn_arm_version }}
         creates=/usr/local/bin/openvpn
  notify: restart openvpn
- name: OpenVPN | ARM | Create base directories
  file: state=directory path=/etc/openvpn owner=root group=root
