---
# File: main.yml
# Type: handler
# Part: OpenVPN

- name: start openvpn
  service: name=openvpn state=started

- name: restart openvpn
  service: name=openvpn state=restarted

- name: restart monit
  service: name=monit state=restarted
