---
# File: main.yml
# Type: handler
# Part: Varnish

- name: start varnish
  service: name=varnish start=started

- name: restart varnish
  service: name=varnish state=restarted

- name: reload varnish
  service: name=varnish state=reloaded
