---
# File: main.yml
# Type: task
# Part: Ansible/Accelerated


## Install
- name: Accelerated | Install required packages
  apt: name={{ item }} state=latest
  with_items:
    - python-software-properties
    - python-pip
- name: Accelerated | Install keyczar
  pip: name=python-keyczar state=present
  when: ansible_distribution_release == 'precise'
- name: Accelerated | Install keyczar pre
  pip: name=python-keyczar state=present extra_args=--pre
  when: ansible_distribution_release == 'trusty'
- name: Accelerated | Open port for keyczar
  command: ufw allow 5099/tcp
  ignore_errors: True
  when: ansible_distribution == 'Ubuntu'
